Showcase Message Exchange Functionality
ADORSYS-GIS/wallet-vc pull request #2
Opened 2024-11-05 12:11 UTC by forkimenjeckayang

This PR , adds functionality to the sample wallet application in terms of messaging functionality.  The core message sending  functionality  will be handled later.
Keeping this simple at the start...

2024-11-05 12:27 UTC, forkimenjeckayang commented
Closses: adorsys/eudiw-app#223

2024-11-06 09:13 UTC, Awambeng requested changes

2024-11-06 09:13 UTC, Awambeng commented on src/pages/ContactInfoPage.tsx
> +          setSnackbarMessage("Contact and messages removed successfully."); // Set success message
Instead of using the Snackbar directly, you can use our own status-library and event-bus library for handling notifications.

2024-11-06 09:13 UTC, Awambeng commented on src/pages/ContactInfoPage.tsx
> +      <Snackbar
same here make use of our libraries

2024-11-18 08:08 UTC, Awambeng requested changes
Please adjust the height of the pages so that users don’t need to scroll to see elements like the Navbar

2024-11-18 08:10 UTC, Awambeng commented on src/pages/ChatPage.tsx
> +          eventBus.off(getAllByContactIdChannel, handleMessagesReceived);
Please review how messages are fetched and displayed. When a new message is added and the browser is refreshed, the messages seem to get swapped, which is not ideal. Ensure that new messages appear in the same order they were added.

2024-11-19 08:00 UTC, Awambeng commented
> Please adjust the height of the pages so that users don’t need to scroll to see elements like the Navbar

This was solved only on desktop not on mobile devices

Looks good on my Laptop

![image](https://github.com/user-attachments/assets/acf59b83-9597-46e3-add0-bf0386d4eabf)

On mobile devices we still need to scroll down before seeing the NavBar

![image](https://github.com/user-attachments/assets/8ebc80c7-2aa3-4630-8999-3fc8046c207d)

2024-11-19 12:03 UTC, Awambeng approved these changes

2024-11-19 12:03 UTC, merged