Use of the PWA library in the example App
ADORSYS-GIS/wallet-vc pull request #3
Opened 2024-11-07 08:40 UTC by forkimenjeckayang

Closes https://github.com/adorsys/eudiw-app/issues/276

By integrating the usePWA library in the example app with some extra configurations, our application can now be used as a PWA.

2024-11-08 07:19 UTC, forkimenjeckayang commented
Closses: adorsys/eudiw-app#276

2024-11-11 10:12 UTC, IngridPuppet commented on src/App.tsx
> +import { ThemeProvider, createTheme } from "@mui/material/styles";
I'm not against importing the CSS file here, but this makes me think there is still a problem in the usePWA library. Can you update me on how you managed to fix CSS embedding from there?

2024-11-11 10:13 UTC, IngridPuppet commented on src/App.tsx
> +
What is the effect of calling this hook without doing anything of the returned value?

2024-11-11 10:18 UTC, IngridPuppet commented on tsconfig.json
> +, "public/service-worker.js"  ]
Why add this? It is not even a TS file.

2024-11-11 10:22 UTC, IngridPuppet commented on src/index.tsx
> +      >
I'm not prompted to install the PWA. Can you debug my environment whenever possible?

2024-11-12 09:48 UTC, IngridPuppet requested changes
The `usePWA` library should be compatible with minor updates to React 18.
```json
  "peerDependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
```

2024-11-12 10:51 UTC, IngridPuppet approved these changes

2024-11-12 11:09 UTC, merged